import "./globals.css";
import type { Metadata } from "next";

import SessionProvider from "./Providers/SessionProvider";
import ReduxProvider from "./Providers/ReduxProvider";

import InnerLayout from "./InnerLayout";

export const metadata: Metadata = {
  title: "Filmora | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body suppressHydrationWarning={true}>
          <ReduxProvider>
            <InnerLayout>{children}</InnerLayout>
          </ReduxProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
