import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SessionProvider from "./SessionProvider";

import ReduxProvider from "./ReduxProvider";

import InnerRootLayout from "./InnerRootLayout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Filmora | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SessionProvider>
        <body suppressHydrationWarning={true}>
          <ReduxProvider>
            <InnerRootLayout>{children}</InnerRootLayout>
          </ReduxProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
